### ISSUE TITLE
Remove 命令无法使用

### ISSUE THREAD

**Issue by lamons** [Wildog/Ariafred#10]
键入 `aria remove` 之后出现的似乎是搜索含有 'remove' 关键字的任务而不是可移除的任务列表。按 `⌥`+`Enter` 可以正常移除任务。
截图：
![snip20160520_34](https://cloud.githubusercontent.com/assets/5617053/15412703/86a92100-1e21-11e6-8a2b-705bc8cf91e8.png)

**Comment by Wildog** [comment]
不好意思，文档里面写错了，删除的关键词应该是 `rm` 不是 `remove`

**Comment by lamons** [comment]
啊，多谢：）
