### ISSUE TITLE
大量消耗CPU

### ISSUE THREAD

**Issue by sequencer** [Wildog/Ariafred#15]
`19:15:38 background.py:243 ERROR    Command failed with [1] : [u'/usr/bin/python', '/Users/Sequencer/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.5EA3A4CA-E707-4B02-81C5-59A099B0A640/workflow/update.py', u'check', 'Wildog/Ariafred', '1.5.2']
`
应该是检查更新有失败？

**Comment by Wildog** [comment]
1.5.3 修复了，如果自动更新失效了的话，手动下载最新的 release 更新吧
