### ISSUE TITLE
<ProtocolError for token:123456@localhost:6800/jsonrpc: 500 Internal server error>

### ISSUE THREAD

**Issue by yxjxx** [Wildog/Ariafred#2]
If I set a `rpc-secret=123456` in aria2.conf, ariafred can't work and the error message is `<ProtocolError for token:123456@localhost:6800/jsonrpc: 500 Internal server error>`

**Comment by Wildog** [comment]
rpc-secret are not supported in current version(1.1), but will be soon in the next version.
And don't use `jsonrpc` because Ariafred uses xml-rpc, use `rpc` is just fine, take it as an example for rpc setting: `http://localhost:6800/rpc`

**Comment by Wildog** [comment]
@yxjxx rpc-secret support has been added to the latest release(v1.2), please check it out and see the doc for setting.

**Comment by yxjxx** [comment]
for memo

~/Library/Application Support/Alfred 3/Workflow Data/dog.wil.ariafred/settings.json
```
{
  "__workflow_last_version": "1.5.3",
  "rpc_path": "http://localhost:6800/rpc",
  "secret": "123789"
}
```
