### ISSUE TITLE
Authorization failed while downloading from Baiduyun

### ISSUE THREAD

**Issue by homever** [Wildog/Ariafred#3]
Trying to add a baiduyun link, but Ariafred failed in starting task with error message "Authorization failed", yet YAAW works just fine.

**Comment by Wildog** [comment]
试了下直接复制下载地址的话, 在命令行里新建下载也是会报错的, 只有在 YAAW 这种 WebUI 里面才可以正常下载, 可能跟 session 和 cookie 有关. 暂时只能用 [BaiduExporter](https://github.com/acgotaku/BaiduExporter) 插件导出来正常下载.

**Comment by homever** [comment]
多谢
