### ISSUE TITLE
下载的状态能否实时更新呢？

### ISSUE THREAD

**Issue by miniers** [Wildog/Ariafred#7]
如题，如果能加上这个特性，就真的没必要用网页版拉，再次感谢无私奉献

**Comment by Wildog** [comment]
@miniers 这个暂时是不现实的。。。 Alfred 里面显示的内容实际上是静态的，每次你改变输入时才会运行一次 Workflow 脚本来更新内容，而 Workflow 脚本每次运行最多只能提交一次结果给 Alfred
