### ISSUE TITLE
Error in workflow 'dog.wil.ariafred'

### ISSUE THREAD

**Issue by patricorgi** [Wildog/Ariafred#8]
我截了个图：[点这里](https://drive.google.com/file/d/0B3XZV56h92suWkgxRC1saHozNk0/view?usp=sharing)

**Comment by Wildog** [comment]
@hangyiwu 你设置的rpc地址是什么?

**Comment by patricorgi** [comment]
RPC host  http(s)://localhost
RPC port  6800

**Comment by Wildog** [comment]
@hangyiwu 你在 Alfred 里输入 `aria rpc http://localhost:6800/rpc` 设置一下试试

**Comment by patricorgi** [comment]
输入这行命令没有效果。我说一下产生这个错误的过程也许能帮助解决问题：
之前我希望在终端里使用`aria2c`命令下载文件，它总是提示
`IPv4(or IPv6) RPC: failed to bind TCP port 6800 Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause:  Address already in use`. 
所以我在`.aria2/aria2.conf`把端口设置成6152（通过加入一行`rpc-listen-port=6152`），之后执行`aria2c --conf-path="/Users/wuhangyi/.aria2/aria2.conf" -D`，此后就可以在终端中用aria2c + url的命令下载文件了。事后我猜想可能就是ariafred在使用这个端口，因而终端里提示说“Address already in use”，当然我这只是瞎猜。后来ariafred就像这样不能用了。把`rpc-listen-port`改回6800或把这行命令删除都无济于事。
PS：之所以使用6152这个端口，是因为使用surge for mac这个软件。

**Comment by Wildog** [comment]
如果你是通过 ariafred 启动的 aria2c 的话会自动读取配置文件并以 daemon 形式运行 aria2c, 如果你的配置文件里面没有端口设置的话就默认用的 6800, 然后这时你再在终端里面运行 aria2c 的话就会因为已经有一个 aria2c 实例在运行并占有 6800 端口而出错. 
然后很诡异的是我按你的流程走了一遍后, 我的 ariafred 并没有重现你的错误, 你试下在配置文件里把 `rpc-listen-port` 这行删除然后把 `~/Library/Application Support/Alfred 2/Workflow Data/dog.wil.ariafred/settings.json` 这个文件也删除一下试试.

**Comment by patricorgi** [comment]
删除`settings.json`，然后在alfred中选择`Aria2 may not be running, try start it?`之后，提示`Aria2 has started successfully`。但是再从alfred输入aria2仍然提示`Aria2 may not be running, try start it?`

我的配置文件内容如下，是使用少数派[这篇文章](http://sspai.com/32167)中的配置：

```
#用户名
#rpc-user=user
#密码
#rpc-passwd=passwd
#上面的认证方式不建议使用,建议使用下面的token方式
#设置加密的密钥
#rpc-secret=token
#允许roc
enable-rpc=true
#允许所有来源, web界面跨域权限需要
rpc-allow-origin-all=true
#允许外部访问，false的话只监听本地端口
rpc-listen-all=true
#RPC端口, 仅当默认端口被占用时修改
#rpc-listen-port=6800
#最大同时下载数(任务数), 路由建议值: 3
max-concurrent-downloads=5
#断点续传
continue=true
#同服务器连接数
max-connection-per-server=5
#最小文件分片大小, 下载线程数上限取决于能分出多少片, 对于小文件重要
min-split-size=10M
#单文件最大线程数, 路由建议值: 5
split=10
#下载速度限制
max-overall-download-limit=0
#单文件速度限制
max-download-limit=0
#上传速度限制
max-overall-upload-limit=0
#单文件速度限制
max-upload-limit=0
#断开速度过慢的连接
#lowest-speed-limit=0
#验证用，需要1.16.1之后的release版本
#referer=*
#文件保存路径, 默认为当前启动位置
dir=/Users/wuhangyi/Downloads
#文件缓存, 使用内置的文件缓存, 如果你不相信Linux内核文件缓存和磁盘内置缓存时使用, 需要1.16及以上版本
#disk-cache=0
#另一种Linux文件缓存方式, 使用前确保您使用的内核支持此选项, 需要1.15及以上版本(?)
#enable-mmap=true
#文件预分配, 能有效降低文件碎片, 提高磁盘性能. 缺点是预分配时间较长
#所需时间 none < falloc ? trunc « prealloc, falloc和trunc需要文件系统和内核支持
file-allocation=prealloc

```

**Comment by Wildog** [comment]
如果 ariafred 依然这么提示的话, 很有可能是 aria2c 依然没有监听在 6800 端口上, 你在终端里试一下 `sudo lsof -i -n -P | grep aria2c` 看看现在运行的 aria2c 到底监听的哪个 TCP 端口

**Comment by hangyiwu** [comment]
非常感谢，问题解决了。不过我还想请教一下，如果终端里无法用aria2c <URL>下载，如何用aria2c下载普通文件呢（非网盘文件）。

**Comment by patricorgi** [comment]
非常感谢！问题解决了，很耐心。

**Comment by Wildog** [comment]
@hangyiwu 你可以直接在 ariafred 里新建下载: `aria add <URL>`, 详细使用可以看 [readme](https://github.com/Wildog/Ariafred/blob/master/README.md) 或者[我的博客](http://wil.dog/ariafred/)
